name: Pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Install dependencies
        run: |
          pip install black flake8 pylint pydocstyle safety
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
